In [2]:
import numpy as np

The Basics

In [3]:
a = np.array([1,2 ,3])
print(a.ndim) 

1


ndim gets the number of the dimensions of the array

In [4]:
b = np.array([[9.0, 8.4 , 11.1], [5.5, 6.7 , 8.9]])
print(b.shape)

(2, 3)


In [5]:
# Get the type
a.dtype

dtype('int64')

We can specifiy the type as well

In [6]:
a = np.array([1, 2,3 ], dtype= 'int16')
a.dtype

dtype('int16')

Accessing/Changing specific elements, rows, columns, etc

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get a specific element [r, c]
print(a[1,3])

11


In [9]:
# Get a specific row 
print(a[0, :])

[1 2 3 4 5 6 7]


In [10]:
# Get a specific column
print(a[:, 3])

[ 4 11]


In [11]:
# Getting a little more fancy [startindex:endindex:stepsize]

print(a[0, 1:-1 : 2])

[2 4 6]


In [12]:
# Change an element
a[1,-1 ] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


In [13]:
# Change an entire column

a[:, 2] = [88, 99]
print(a)

[[ 1  2 88  4  5  6  7]
 [ 8  9 99 11 12 13 20]]


*3-d example

In [14]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# Get specific element (work outside in)
b[1,0,0]

np.int64(5)

Initializing Different Types of Arrays

In [16]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3) , dtype='int16')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [17]:
# All 1s matrix
np.ones(8)
print(np.ones((2, 2), dtype='int32'))

[[1 1]
 [1 1]]


In [18]:
# Any other number
np.full((2,2), 5, dtype='float32')

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [19]:
# Any other number (full_like)
print(np.full_like(a, 4))
# Or 
print(np.full(a.shape, 4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [20]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.48055242, 0.21272988],
       [0.04610456, 0.07571654],
       [0.38892277, 0.10903288],
       [0.52306379, 0.65487112]])

In [21]:
# Random Integer values
print(np.random.randint(7, size=(3,3)), end="\n\n")

print(np.random.randint(8,12, size=(2,2)))

[[2 4 5]
 [5 2 2]
 [3 3 2]]

[[ 9 10]
 [ 9  9]]


In [22]:
# The identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
print(np.repeat(arr, 3))
r1 = np.repeat(arr, 3, axis=0)
r1

[1 1 1 2 2 2 3 3 3]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:
output = np.ones((5,5))
print(output)

out_zero = np.zeros((3,3))
out_zero[1,1] = 9

output[1: 4, 1:4] = out_zero

output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays!!!

In [25]:
#DO NOT Do THIS
a = np.array([1,2,3])
b = a
b[0] = 100
print(a, b)

[100   2   3] [100   2   3]


In [26]:
# Instead do this
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a, b)

[1 2 3] [100   2   3]


Mathematics

In [27]:
a = np.array([1,2,3,4])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [28]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [29]:
# Power
a ** 2

array([ 1,  4,  9, 16])

In [30]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [36]:
#Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
# Find the inverse

c = np.array([[1,2], [3,4]]) # determinant should not be zero
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statistics

In [45]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats) # 1
np.min(stats, axis=1) # [1, 4] min of each row
np.min(stats, axis=0) # [1, 2, 3] min of each column
np.max(stats, axis=0) # [4, 5, 6] max of each column

array([4, 5, 6])

In [51]:
np.sum(stats) # 21
np.sum(stats, axis=0) # [5, 7, 9] sum of each column
np.sum(stats, axis=1) # [6, 15] sum of each row

array([ 6, 15])

Reorganizing Arrays

In [53]:
# Reshaping
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2]) #[[1,2,3,4], [5,6,7,8]]
np.vstack([v2, v1]) #[[5,6,7,8], [1,2,3,4]]
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1, h2]) # [[1,1,1,1,0,0], [1,1,1,1,0,0]]
np.hstack([h2, h1]) # [[0,0,1,1,1,1], [0,0,1,1,1,1]]

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

Miscellaneous

Load Data from File

In [60]:
# Load data from file
fileData = np.genfromtxt('data.txt', delimiter=',', dtype='int32') # one way to type cast
fileData = fileData.astype('int32') # another way to type cast
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

Boolean Masking and Advanced Indexing

In [61]:
fileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [63]:
fileData[fileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# Index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,5,-1]] # [1,6,9]

array([1, 6, 9])

In [ ]:
np.all(fileData > 50, axis=0) # Columns with value > 50
np.all(fileData > 50 , axis=1) # Rows with value > 50

array([False, False, False])

In [69]:
(~((fileData > 50) & (fileData < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])